make: 
	python dataClassifier.py -c naiveBayes -d faces -t 45
	python dataClassifier.py -c naiveBayes -d faces -t 90
	python dataClassifier.py -c naiveBayes -d faces -t 135
	python dataClassifier.py -c naiveBayes -d faces -t 180
	python dataClassifier.py -c naiveBayes -d faces -t 226
	python dataClassifier.py -c naiveBayes -d faces -t 270
	python dataClassifier.py -c naiveBayes -d faces -t 315
	python dataClassifier.py -c naiveBayes -d faces -t 361
	python dataClassifier.py -c naiveBayes -d faces -t 406
	python dataClassifier.py -c naiveBayes -d faces -t 451
	python dataClassifier.py -c naiveBayes -d digits -t 500
	python dataClassifier.py -c naiveBayes -d digits -t 1000
	python dataClassifier.py -c naiveBayes -d digits -t 1500
	python dataClassifier.py -c naiveBayes -d digits -t 2000
	python dataClassifier.py -c naiveBayes -d digits -t 2500
	python dataClassifier.py -c naiveBayes -d digits -t 3000
	python dataClassifier.py -c naiveBayes -d digits -t 3500
	python dataClassifier.py -c naiveBayes -d digits -t 4000
	python dataClassifier.py -c naiveBayes -d digits -t 4500
	python dataClassifier.py -c naiveBayes -d digits -t 5000

t:
	make
	make
	make
	make
	make
